version: '3.5'

# 日志配置
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "10"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}


services:

  ### GPTLINK ################################################
  gptlink:
    image: overnick/gptlink:1.0
    #platform: linux/x86_64
    volumes:
      - ${DATA_PATH}/logs/server:/app/gptserver/runtime/logs
      - ${DATA_PATH}/logs/nginx:/var/log/nginx
    environment:
      - APP_NAME=${GPTLINK_APP_NAME}
      - APP_URL=${GPTLINK_APP_URL}
      - JWT_SECRET=${GPTLINK_JWT_SECRET}
      - ADMIN_USERNAME=${GPTLINK_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${GPTLINK_ADMIN_PASSWORD}
      - DB_HOST=${GPTLINK_DB_HOST:-mysql}
      - DB_PORT=${GPTLINK_DB_PORT:-3306}
      - DB_DATABASE=${GPTLINK_DB_DATABASE}
      - DB_USERNAME=${GPTLINK_DB_USERNAME}
      - DB_PASSWORD=${GPTLINK_DB_PASSWORD}
      - REDIS_HOST=${GPTLINK_REDIS_HOST:-redis}
      - REDIS_AUTH=${GPTLINK_REDIS_AUTH:-(null)}
      - REDIS_PORT=${GPTLINK_REDIS_PORT:-6379}
      - OPENAI_HOST=${OPENAI_HOST:-api.gpt-link.com}
      - OPENAI_PORT=${OPENAI_PORT:-443}
      - OPENAI_PROXY_HOST=${OPENAI_PROXY_HOST:-}
      - OPENAI_PROXY_PORT=${OPENAI_PROXY_PORT:-}
    ports:
      - "${GPTLINK_PORT:-80}:80"
    networks:
      - backend
    logging: *default-logging

  ### Redis ################################################
  redis:
    build: ./redis
    #platform: linux/x86_64
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - backend
    logging: *default-logging

  ### MySQL ################################################
  mysql:
    build:
      context: ./mysql
    #platform: linux/x86_64
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-gptlink}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - backend
    logging: *default-logging
