FROM overnick/gptlink:${GPTLINK_VERSION:-latest}

# 证书文件放于 docker-compose/gptlink/ssl/website.key 与 docker-compose/gptlink/ssl/website.pem
# 如需开启 ssl，请打开以下注释

# COPY conf/nginx-default.conf /etc/nginx/conf.d/default.conf
# COPY ssl /etc/nginx/ssl
